apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdoubrem-test
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gdoubrem-playground
  template:
    metadata:
      labels:
        app: gdoubrem-playground
    spec:
      containers:
      - name: gdoubrem-playground
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: gdoubrem-playground
  namespace: dev
spec:
  selector:
    app: gdoubrem-playground
  ports:
  - port: 8888
    targetPort: 8888
